name: my-check

on:
  - push
  - pull_request

jobs:
  buld:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          build-root-directory: ./app

      - name: build
        run: make build
        working-directory: ./app

      - name: run tests
        run: make test
        working-directory: ./app

      - name: run checkstyleMain
        run: make lint
        working-directory: ./app

      - name: publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: make report
          coverageLocations: build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          workingDirectory: ${{github.workspace}}/app
